Correct snapshot_validator to also work when empty documents are found.
helm-unittest/helm-unittest pull request #220
Opened 2023-09-19 08:49 UTC by matthyx

Related to https://github.com/helm-unittest/helm-unittest/pull/198
Fixes https://github.com/helm-unittest/helm-unittest/issues/191

I need the same fix for `snapshot_validator` since it's failing when templates are returning empty string (which is the intended output sometimes).

2023-09-28 13:31 UTC, matthyx commented
@quintush can you have a look?

2023-10-18 08:11 UTC, matthyx commented
@quintush please we really need this functionality, just take a look and let me know...

2023-10-18 12:15 UTC, vladklokun commented
Hi!

I would also like to mention that I’m also interested in having this upstreamed, because it fails our tests for resources that are conditionally created.

Let me know if I can help having this merged. Thank you!

2023-11-03 22:22 UTC, quintush requested changes

2023-11-03 22:22 UTC, quintush commented on pkg/unittest/validators/snapshot_validator.go
> +	validateSuccess := true
validateSuccess := len(manifests) == 0

Set the validationSucces, based on the length.
This way when a manifest is found, we still have the same validation.

2023-11-04 06:53 UTC, matthyx commented
https://github.com/helm-unittest/helm-unittest/pull/233 supercedes this

2023-11-04 06:53 UTC, closed without merging