feat(issue-499): yaml escape issue
helm-unittest/helm-unittest pull request #521
Opened 2024-12-22 16:31 UTC by ivankatliarchuk

resolves #issue-499

2025-01-02 13:55 UTC, ivankatliarchuk commented
Hi @quintush . When you have time, please have a look. Ready to be merged

2025-01-06 21:02 UTC, quintush requested changes

2025-01-06 21:02 UTC, quintush commented on internal/common/utilities_ymlescape_test.go
> +package common
Please use common_test as package for the tests.

It helps to not fully go wild on separated files and create awareness on executing methods outside a package

2025-01-06 21:02 UTC, quintush commented on pkg/unittest/test_runner_fixture_test.go
As there is already a unittest_test package, I would suggest to keep these tests in the same file.

Based on comment blocks and naming conventions on tests
we can clarify the goal of the tests.

2025-01-06 21:02 UTC, quintush commented on internal/common/utilities_ymlescape.go
> +// yaml unmaintained library issue https://github.com/go-yaml/yaml/pull/862
Please check if the sig yaml library (sigs.k8s.io/yaml, which contains a copy of the go-yaml) also still has this issue.

Currently looking for a way to fully migrate to the sig yaml library.

2025-01-06 21:47 UTC, ivankatliarchuk commented on internal/common/utilities_ymlescape.go
> +// yaml unmaintained library issue https://github.com/go-yaml/yaml/pull/862
sigs.k8s.io is just a wrapper unfortunately. 

![Screenshot 2025-01-06 at 21 43 12](https://github.com/user-attachments/assets/4a322e85-08af-4b4a-99dd-ea0396f3730d)

I was thinking about forking `gopkg.in/yaml.v3` as an option. Not too much work

2025-01-06 22:00 UTC, ivankatliarchuk commented on pkg/unittest/test_runner_fixture_test.go
Sure. moved to `unitetest_test`

2025-01-06 22:00 UTC, ivankatliarchuk commented on internal/common/utilities_ymlescape_test.go
> +package common
changed to commot_test

2025-01-06 22:03 UTC, ivankatliarchuk commented on internal/common/utilities_ymlescape.go
> +// yaml unmaintained library issue https://github.com/go-yaml/yaml/pull/862
This yaml.Node is another problem )). There are few dependencies, they are super old, and they rely on yaml.v3 structs.... So it's like ripping off bones.

With this pull request, main target was to cover functionality with tests. So there is quite a decent coverage. Should simplify moving to another library when ready. I have no solution at the mean time unfortunately.

2025-01-07 13:34 UTC, ivankatliarchuk commented on internal/common/utilities_ymlescape.go
> +// yaml unmaintained library issue https://github.com/go-yaml/yaml/pull/862
> Please check if the sig yaml library (sigs.k8s.io/yaml, which contains a copy of the go-yaml) also still has this issue.

I was not able to make it work, due to other dependencies explicitly require `gopkg.in/yaml.v3.Node` for example.

What do you think? Shell we merge this one in, and you will try to swap libraries, this will require some rewrite to how helm-unittest does yaml node traversing? With this pull request we going to have a test coverage that new library need to satisfy.

I could fork `"gopkg.in/yaml.v3` and fix it there, as alternative solution.

2025-01-08 21:42 UTC, quintush commented on internal/common/utilities_ymlescape.go
> +// yaml unmaintained library issue https://github.com/go-yaml/yaml/pull/862
This is good for the goal we want to achieve.

About forking or using another yaml library, I'm Currently looking closely to which library helm is using. This to prevent a different outcome.

Greetings,
@quintush

2025-01-08 21:45 UTC, merged